version: "3.5"

x-tpl:
  kafka-common: &kafka-common
    image: bitnami/kafka:3.6
  environment:  &environment
    KAFKA_KRAFT_CLUSTER_ID: abcdefghijklmnopqrstuv
    KAFKA_CFG_PROCESS_ROLES: "controller,broker"
    KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "0@kafka-0:9093,1@kafka-1:9093,2@kafka-2:9093"
    KAFKA_CFG_LISTENERS: "SASL://:9094,CONTROLLER://:9093,INTERNAL://:9092"
    KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,SASL:SASL_PLAINTEXT,INTERNAL:PLAINTEXT"
    KAFKA_CFG_ADVERTISED_LISTENERS: "SASL://:9094,INTERNAL://9092"
    KAFKA_CLIENT_LISTENER_NAME: "SASL"
    KAFKA_CLIENT_USERS: "admin"
    KAFKA_CLIENT_PASSWORDS: "admin-secret"
    KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
    KAFKA_CFG_INTER_BROKER_LISTENER_NAME: "INTERNAL"
 #   KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL: "PLAIN"



services:
  kafka-ui:
    image: provectuslabs/kafka-ui:master
    container_name: kafka-ui
    ports:
      - "8080:8080"

    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL: SASL_PLAINTEXT
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-0:9094
      KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM: PLAIN
      KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG: 'org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="admin-secret";'
      AUTH_TYPE: "LOGIN_FORM"
      SPRING_SECURITY_USER_NAME: admin
      SPRING_SECURITY_USER_PASSWORD: pass
  kafka-0:
    hostname: kafka-0
    <<: *kafka-common
    ports:
      - 9092
      - 9094:9094
    environment:
      <<: *environment
      KAFKA_CFG_NODE_ID: "0"
      KAFKA_CFG_ADVERTISED_LISTENERS: "SASL://:9094,INTERNAL://kafka-0:9092"
  kafka-1:
    hostname: kafka-1 
    <<: *kafka-common
    ports:
      - 9092
    environment:
      <<: *environment
      KAFKA_CFG_NODE_ID: "1"
      KAFKA_CFG_ADVERTISED_LISTENERS: "SASL://:9094,INTERNAL://kafka-1:9092"

  kafka-2:
    hostname: kafka-2
    <<: *kafka-common
    ports:
      - 9092
    environment:
      <<: *environment
      KAFKA_CFG_NODE_ID: "2"
      KAFKA_CFG_ADVERTISED_LISTENERS: "SASL://:9094,INTERNAL://kafka-2:9092"


  producer:
    image: bitnami/python:3.9
    container_name: producer
    command: "sh -c 'pip install -r requirements.txt && python producer.py'"

    environment:
      BOOTSTRAP_SERVERS: kafka-0:9094
      TOPIC_NAME: orders

      SASL_USERNAME: admin
      SASL_PASSWORD: admin-secret
    volumes:
      - .:/app
  consumer:
    image: bitnami/python:3.9
    container_name: consumer
    command: "sh -c 'pip install -r requirements.txt && python consumer.py'"

    environment:
      BOOTSTRAP_SERVERS: kafka-0:9094
      TOPIC_NAME: orders
      GROUP_ID: orders-group

      SASL_USERNAME: admin
      SASL_PASSWORD: admin-secret
    volumes:
      - .:/app